security:
    providers:
        our_db_provider:
            entity:
                class: App\Entity\User
                property: username
    firewalls:
        main:
            pattern: ^/
            #Récupération en base de données
            provider: our_db_provider
            anonymous: ~
            form_login:
                #Vérification et redirection
                login_path: login
                check_path: login
            logout:
                path: logout
                target: home
            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 604800 # 1 week in seconds

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

    encoders:
        #Hasher les mots de passe
        App\Entity\User:
            algorithm: bcrypt

    role_hierarchy:
        #Attribution de plusieurs rôles
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    access_control:
        - {path: ^/admin/, roles: ROLE_ADMIN}
        - { path: ^/editprofile, roles: ROLE_USER}
